spring:
  application:
    name: tg-bot-service
  profiles:
    active: prod

integration:
  rabbit:
    inbound:
      analytics:
        pulse:
          queue: analytics-response-pulse-queue
          routing-key: response.pulse
        news:
          queue: analytics-response-news-queue
          routing-key: response.news
      user-service:
        exchange: user-notifications-exchange
        favourite-stocks:
          queue: user-service-favourite-stocks
          routing-key: userService.favourite-stocks
        user-update:
          queue: user-service-user-update
          routing-key: userService.user-update
    outbound:
      notification:
        queue: notification-queue
      analytics:
        exchange: analytics-exchange
        queue: analytics-request-queue
        routing-key: request
      tg-bot:
        favourite-stocks:
          queue: tg-bot-favorite-stocks
          routing-key: tgBot.favourite-stocks
        user-update:
          queue: tg-bot-user-update
          routing-key: tgBot.user-update

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: "/v1/internal/actuator"
