spring:
  profiles:
    active: local

integration:
  rabbit:
    exchanges:
      analytics: analytics-exchange
    queues:
      outbound:
        notification: notification-queue
        analytics:
          request: analytics-request-queue
      inbound:
        analytics:
          pulse: analytics-response-pulse-queue
          news: analytics-response-news-queue
    routing-keys:
      tg-bot:
        request: request
        response:
          pulse: response.pulse
          news: response.news