server:
  port: 8083

bot:
  token: ${BOT_TOKEN}
  name: "lissa_trading_bot"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: tg_bot_db

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: tg_bot_db

security:
  internal:
    token: Iq6Vu8Nz7Xa3Rl9Cm5YbTc2WpDf4Oj5ZfGn1Kh3

cache:
  caffeine:
    expire-after-write: 5 # в минутах
    maximum-size: 100

integration:
  rest:
    auth-service-url: http://localhost:8081
    user-service-url: http://localhost:8080
    tinkoff-api-service-url: http://localhost:8082

telegram-bot:
  notification:
    checkPriceChangesInterval: 60000 # интервал проверки цен, миллисекунды
    priceChangeWindowMinutes: 60 # сравнение цены за час
    criticalPriceChangePercentage: 3 # отклонение на 3% критичное

logging:
  level:
    root: info
  logstash:
    host: localhost  # Хост Logstash
    port: 5000 # Порт Logstash