apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.license.self_generated.type
              value: "basic"
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          volumeMounts:
            - name: esdata
              mountPath: /usr/share/elasticsearch/data
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata