apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-tg-bot
spec:
  selector:
    app: lissa-trading-tg-bot
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
